/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
