cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-large-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier predict /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/imagenet1k-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/darknet19.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/darknet19.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
cat /home/ubuntu/GPU-Sched/Benchmarks/darknet/image-names-medium-full-v100.txt | /home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet detect /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/yolov3-tiny.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/yolov3-tiny.weights
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet rnn generate /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/rnn.cfg /home/ubuntu/GPU-Sched/Benchmarks/darknet/weights/shakespeare.weights -len 100000
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
