/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
/home/ubuntu/GPU-Sched/Benchmarks/darknet/darknet classifier train /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar-cporter.data /home/ubuntu/GPU-Sched/Benchmarks/darknet/cfg/cifar_small.cfg
