nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
nvprof /home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/myocyte/myocyte.out 1000 100 1 &
wait
