/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
/home/rudy/wo/gpu/GPU-Sched/Benchmarks/rodinia_cuda_3.1/cuda/backprop/backprop 524288
